# Generated by Django 4.2.9 on 2024-03-18 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubusers", "0003_userprofile_confirm_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="confirm_password",
        ),
    ]
